package SimpleCalculator;

import javax.swing.JOptionPane;

public class SimpleCalculator_JF extends javax.swing.JFrame {
    public SimpleCalculator_JF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        Tytul = new javax.swing.JLabel();
        PierwLiczba = new javax.swing.JLabel();
        DrugaLiczba = new javax.swing.JLabel();
        TrzeciaLiczba = new javax.swing.JLabel();
        liczbaTxt_1 = new javax.swing.JTextField();
        liczbaTxt_2 = new javax.swing.JTextField();
        liczbaTxt_3 = new javax.swing.JTextField();
        Text_0 = new javax.swing.JLabel();
        Text_1 = new javax.swing.JLabel();
        Text_2 = new javax.swing.JLabel();
        Text_3 = new javax.swing.JLabel();
        Text_4 = new javax.swing.JLabel();
        WynDodawania = new javax.swing.JLabel();
        WynOdejmowania = new javax.swing.JLabel();
        WynMnozenia = new javax.swing.JLabel();
        WynDzielenia = new javax.swing.JLabel();
        Dodaj = new javax.swing.JButton();
        Odejmij = new javax.swing.JButton();
        Pomnóż = new javax.swing.JButton();
        Podziel = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tytul.setText("Prosty kalkulator");

        PierwLiczba.setText("Pierwsza liczba");

        DrugaLiczba.setText("Druga liczba");

        TrzeciaLiczba.setText("Trzecia liczba");

        liczbaTxt_1.setBackground(new java.awt.Color(51, 255, 51));

        liczbaTxt_2.setBackground(new java.awt.Color(51, 255, 51));

        liczbaTxt_3.setBackground(new java.awt.Color(51, 255, 51));
        liczbaTxt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liczbaTxt_3ActionPerformed(evt);
            }
        });

        Text_0.setText("Działania na liczbach:");

        Text_1.setText("Dodawanie (a+b+c):");

        Text_2.setText("Odejmowanie (a-b-c): ");

        Text_3.setText("Mnożenie (a*b*c): ");

        Text_4.setText("Dzielenie (a / b): ");

        WynDodawania.setBackground(new java.awt.Color(51, 204, 0));

        Dodaj.setText("Dodaj");
        Dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajActionPerformed(evt);
            }
        });

        Odejmij.setText("Odejmij");
        Odejmij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdejmijActionPerformed(evt);
            }
        });

        Pomnóż.setText("Pomnóż");
        Pomnóż.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PomnóżActionPerformed(evt);
            }
        });

        Podziel.setText("Podziel");
        Podziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PodzielActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TrzeciaLiczba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PierwLiczba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DrugaLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(liczbaTxt_1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(liczbaTxt_2)
                            .addComponent(liczbaTxt_3)))
                    .addComponent(Text_0)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_1)
                            .addComponent(Text_2)
                            .addComponent(Text_3)
                            .addComponent(Text_4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(WynDodawania, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                            .addComponent(WynOdejmowania, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WynMnozenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WynDzielenia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Odejmij)
                            .addComponent(Dodaj)
                            .addComponent(Pomnóż)
                            .addComponent(Podziel))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PierwLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liczbaTxt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liczbaTxt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DrugaLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrzeciaLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liczbaTxt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Text_0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(WynDodawania)
                        .addComponent(Dodaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Odejmij)
                    .addComponent(Text_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(WynOdejmowania))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pomnóż)
                    .addComponent(Text_3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WynMnozenia, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Podziel)
                    .addComponent(Text_4)
                    .addComponent(WynDzielenia, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void liczbaTxt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liczbaTxt_3ActionPerformed
    }//GEN-LAST:event_liczbaTxt_3ActionPerformed

    private void DodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajActionPerformed
       String zwroconyWynik = dodajLiczby(liczbaTxt_1.getText(), 
                                          liczbaTxt_2.getText(), 
                                          liczbaTxt_3.getText());
               WynDodawania.setText(zwroconyWynik);
    }//GEN-LAST:event_DodajActionPerformed

    private void OdejmijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdejmijActionPerformed
       String zwroconyWynik = odejmijLiczby(liczbaTxt_1.getText(), 
                                          liczbaTxt_2.getText(), 
                                          liczbaTxt_3.getText());
               WynOdejmowania.setText(zwroconyWynik);
    }//GEN-LAST:event_OdejmijActionPerformed

    private void PomnóżActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PomnóżActionPerformed
           String zwroconyWynik = pomnozLiczby(liczbaTxt_1.getText(), 
                                          liczbaTxt_2.getText(), 
                                          liczbaTxt_3.getText());
               WynMnozenia.setText(zwroconyWynik);
    }//GEN-LAST:event_PomnóżActionPerformed

    private void PodzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PodzielActionPerformed
        String zwroconyWynik = podzielLiczby(liczbaTxt_1.getText(), 
                                          liczbaTxt_2.getText(), 
                                          liczbaTxt_3.getText());
               WynDzielenia.setText(zwroconyWynik);
    }//GEN-LAST:event_PodzielActionPerformed
// dodawania
    private void dodajLiczby(java.awt.event.ActionEvent evt) {
        String zwroconyWynik = dodajLiczby(liczbaTxt_1.getText(), liczbaTxt_2.getText(), liczbaTxt_3.getText());
        WynDodawania.setText(zwroconyWynik);
    }
        
    private String dodajLiczby(String liczba1, String liczba2, String liczba3) {
        String wynikDodawaniaStr = null;
        try {
            int l1 = Integer.valueOf(liczba1);
            int l2 = Integer.valueOf(liczba2);
            int l3 = Integer.valueOf(liczba3);
            int WynDodawania = l1 + l2 + l3;
            wynikDodawaniaStr = String.valueOf(WynDodawania);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tyllko liczby całkowite");
        }
        return wynikDodawaniaStr;
    }
// odejmowanie
    private void odejmijLiczby(java.awt.event.ActionEvent evt) {
        String zwroconyWynik = odejmijLiczby(liczbaTxt_1.getText(), liczbaTxt_2.getText(), liczbaTxt_3.getText());
        WynOdejmowania.setText(zwroconyWynik);
    }
    
    private String odejmijLiczby(String liczba1, String liczba2, String liczba3){
        String wynikOdejmowaniaStr = null;
        try {
            int l1 = Integer.valueOf(liczba1);
            int l2 = Integer.valueOf(liczba2);
            int l3 = Integer.valueOf(liczba3);
            int WynikOdejmowania = l1 - l2 - l3;
            wynikOdejmowaniaStr = String.valueOf(WynikOdejmowania);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tyllko liczby całkowite");
        }
        return wynikOdejmowaniaStr;
    }
// mnozenie
    private void pomnozLiczby(java.awt.event.ActionEvent evt) {
        String zwroconyWynik = pomnozLiczby(liczbaTxt_1.getText(), liczbaTxt_2.getText(), liczbaTxt_3.getText());
        WynMnozenia.setText(zwroconyWynik);
    }
    
    private String pomnozLiczby(String liczba1, String liczba2, String liczba3){
        String wynikMnozeniaStr = null;
        try {
            int l1 = Integer.valueOf(liczba1);
            int l2 = Integer.valueOf(liczba2);
            int l3 = Integer.valueOf(liczba3);
            int WynikMnozenia = l1 * l2 * l3;
            wynikMnozeniaStr = String.valueOf(WynikMnozenia);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tyllko liczby całkowite");
        }
        return wynikMnozeniaStr;
    }

// dzielenie
    private void podzielLiczby(java.awt.event.ActionEvent evt) {
        String zwroconyWynik = podzielLiczby(liczbaTxt_1.getText(), liczbaTxt_2.getText(), liczbaTxt_3.getText());
        WynDzielenia.setText(zwroconyWynik);
    }
    
    private String podzielLiczby(String liczba1, String liczba2, String liczba3){
        String wynikDzieleniaStr = null;
        try {
            int l1 = Integer.valueOf(liczba1);
            int l2 = Integer.valueOf(liczba2);
            double WynikDzielenia = l1 / l2;
            wynikDzieleniaStr = String.valueOf(WynikDzielenia);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Tyllko liczby całkowite");
        }
        return wynikDzieleniaStr;
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SimpleCalculator_JF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dodaj;
    private javax.swing.JLabel DrugaLiczba;
    private javax.swing.JButton Odejmij;
    private javax.swing.JLabel PierwLiczba;
    private javax.swing.JButton Podziel;
    private javax.swing.JButton Pomnóż;
    private javax.swing.JLabel Text_0;
    private javax.swing.JLabel Text_1;
    private javax.swing.JLabel Text_2;
    private javax.swing.JLabel Text_3;
    private javax.swing.JLabel Text_4;
    private javax.swing.JLabel TrzeciaLiczba;
    private javax.swing.JLabel Tytul;
    private javax.swing.JLabel WynDodawania;
    private javax.swing.JLabel WynDzielenia;
    private javax.swing.JLabel WynMnozenia;
    private javax.swing.JLabel WynOdejmowania;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField liczbaTxt_1;
    private javax.swing.JTextField liczbaTxt_2;
    private javax.swing.JTextField liczbaTxt_3;
    // End of variables declaration//GEN-END:variables
}
