package main.java.SimpleCalculator;

import java.math.BigDecimal;
import java.math.RoundingMode;
import javax.swing.JOptionPane;

public class SimpleCalculator_JF extends javax.swing.JFrame {

    public SimpleCalculator_JF() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        Tytul = new javax.swing.JLabel();
        PierwLiczba = new javax.swing.JLabel();
        DrugaLiczba = new javax.swing.JLabel();
        TrzeciaLiczba = new javax.swing.JLabel();
        liczbaTxt_1 = new javax.swing.JTextField();
        liczbaTxt_2 = new javax.swing.JTextField();
        liczbaTxt_3 = new javax.swing.JTextField();
        Text_0 = new javax.swing.JLabel();
        Text_1 = new javax.swing.JLabel();
        Text_2 = new javax.swing.JLabel();
        Text_3 = new javax.swing.JLabel();
        Text_4 = new javax.swing.JLabel();
        additionResult = new javax.swing.JLabel();
        subtractionResult = new javax.swing.JLabel();
        multiplicationResult = new javax.swing.JLabel();
        divisionResult = new javax.swing.JLabel();
        Dodaj = new javax.swing.JButton();
        Odejmij = new javax.swing.JButton();
        Pomnóż = new javax.swing.JButton();
        Podziel = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tytul.setText("Prosty kalkulator");

        PierwLiczba.setText("Pierwsza liczba(a)");

        DrugaLiczba.setText("Druga liczba(b)");

        TrzeciaLiczba.setText("Trzecia liczba(c)");

        liczbaTxt_1.setBackground(new java.awt.Color(51, 255, 51));

        liczbaTxt_2.setBackground(new java.awt.Color(51, 255, 51));

        liczbaTxt_3.setBackground(new java.awt.Color(51, 255, 51));
        liczbaTxt_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liczbaTxt_3ActionPerformed(evt);
            }
        });

        Text_0.setText("Działania na liczbach:");

        Text_1.setText("Dodawanie (a+b+c):");

        Text_2.setText("Odejmowanie (a-b-c): ");

        Text_3.setText("Mnożenie (a*b*c): ");

        Text_4.setText("Dzielenie (a / b): ");

        additionResult.setBackground(new java.awt.Color(51, 204, 0));

        Dodaj.setText("Dodaj");
        Dodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DodajActionPerformed(evt);
            }
        });

        Odejmij.setText("Odejmij");
        Odejmij.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OdejmijActionPerformed(evt);
            }
        });

        Pomnóż.setText("Pomnóż");
        Pomnóż.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PomnóżActionPerformed(evt);
            }
        });

        Podziel.setText("Podziel");
        Podziel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PodzielActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TrzeciaLiczba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PierwLiczba, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DrugaLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(liczbaTxt_1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(liczbaTxt_2)
                            .addComponent(liczbaTxt_3)))
                    .addComponent(Text_0)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Text_1)
                            .addComponent(Text_2)
                            .addComponent(Text_3)
                            .addComponent(Text_4))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(additionResult, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE))
                            .addComponent(subtractionResult, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(multiplicationResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(divisionResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Odejmij)
                            .addComponent(Dodaj)
                            .addComponent(Pomnóż)
                            .addComponent(Podziel))))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(Tytul, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PierwLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liczbaTxt_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(liczbaTxt_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DrugaLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TrzeciaLiczba, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(liczbaTxt_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(Text_0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(additionResult)
                        .addComponent(Dodaj))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(Text_1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Odejmij)
                    .addComponent(Text_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subtractionResult))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pomnóż)
                    .addComponent(Text_3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(multiplicationResult, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Podziel)
                    .addComponent(Text_4)
                    .addComponent(divisionResult, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void liczbaTxt_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liczbaTxt_3ActionPerformed
    }//GEN-LAST:event_liczbaTxt_3ActionPerformed

    private void DodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DodajActionPerformed
        String addition = additionNumbers(liczbaTxt_1.getText(),
                liczbaTxt_2.getText(),
                liczbaTxt_3.getText());
        additionResult.setText(addition);
    }//GEN-LAST:event_DodajActionPerformed

    private void OdejmijActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OdejmijActionPerformed
        String subtraction = subtractionNumbers(liczbaTxt_1.getText(),
                liczbaTxt_2.getText(),
                liczbaTxt_3.getText());
        subtractionResult.setText(subtraction);
    }//GEN-LAST:event_OdejmijActionPerformed

    private void PomnóżActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PomnóżActionPerformed
        String multiplication = multiplicationNumbers(liczbaTxt_1.getText(),
                liczbaTxt_2.getText(),
                liczbaTxt_3.getText());
        multiplicationResult.setText(multiplication);
    }//GEN-LAST:event_PomnóżActionPerformed

    private void PodzielActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PodzielActionPerformed
        String division = divisionNumbers(liczbaTxt_1.getText(), liczbaTxt_2.getText());
        divisionResult.setText(division);
    }//GEN-LAST:event_PodzielActionPerformed

    private String additionNumbers(String liczba1, String liczba2, String liczba3) {
        try {
            BigDecimal l1 = new BigDecimal(liczba1);
            BigDecimal l2 = new BigDecimal(liczba2);
            BigDecimal l3 = new BigDecimal(liczba3);
            BigDecimal wynik = l1.add(l2).add(l3);
            return wynik.toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Nie prawidłowy format liczby");
        }
        return "";
    }

    private String subtractionNumbers(String liczba1, String liczba2, String liczba3) {
        try {
            BigDecimal l1 = new BigDecimal(liczba1);
            BigDecimal l2 = new BigDecimal(liczba2);
            BigDecimal l3 = new BigDecimal(liczba3);
            BigDecimal wynik = l1.subtract(l2).subtract(l3);
            return wynik.toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Nie prawidłowy format liczby");
        }
        return "";
    }

    private String multiplicationNumbers(String liczba1, String liczba2, String liczba3) {
        try {
            BigDecimal l1 = new BigDecimal(liczba1);
            BigDecimal l2 = new BigDecimal(liczba2);
            BigDecimal l3 = new BigDecimal(liczba3);
            BigDecimal wynik = l1.multiply(l2).multiply(l3);
            return wynik.toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Nie prawidłowy format liczby");
        }
        return "";
    }

    private String divisionNumbers(String liczba1, String liczba2) {
        try {
            BigDecimal l1 = new BigDecimal(liczba1);
            BigDecimal l2 = new BigDecimal(liczba2);
            BigDecimal wynik = l1.divide(l2, 2, RoundingMode.HALF_UP);
            return wynik.toString();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Nie prawidłowy format liczby");
        }
        return "";
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimpleCalculator_JF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new SimpleCalculator_JF().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Dodaj;
    private javax.swing.JLabel DrugaLiczba;
    private javax.swing.JButton Odejmij;
    private javax.swing.JLabel PierwLiczba;
    private javax.swing.JButton Podziel;
    private javax.swing.JButton Pomnóż;
    private javax.swing.JLabel Text_0;
    private javax.swing.JLabel Text_1;
    private javax.swing.JLabel Text_2;
    private javax.swing.JLabel Text_3;
    private javax.swing.JLabel Text_4;
    private javax.swing.JLabel TrzeciaLiczba;
    private javax.swing.JLabel Tytul;
    private javax.swing.JLabel additionResult;
    private javax.swing.JLabel divisionResult;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField liczbaTxt_1;
    private javax.swing.JTextField liczbaTxt_2;
    private javax.swing.JTextField liczbaTxt_3;
    private javax.swing.JLabel multiplicationResult;
    private javax.swing.JLabel subtractionResult;
    // End of variables declaration//GEN-END:variables
}
